full_name = input("Введите ФИО исследователя: ")
date = input("Введите дату (ДД.ММ.ГГГГ): ")
experiment_name = input("Введите название эксперимента: ")
conclusion = input("Введите вывод: ")
with open('journal.txt', 'w', encoding='utf-8') as file:
    file.write("┌" + "─" * 50 + "┐\n")
    file.write("│" + " " * 50 + "│\n")
    file.write("│" + " ЛАБОРАТОРНЫЙ ЖУРНАЛ".ljust(50) + "│\n")
    file.write("│" + " " * 50 + "│\n")
    file.write("├" + "─" * 50 + "┤\n")
    file.write("│" + f" ФИО: {full_name}".ljust(50) + "│\n")
    file.write("│" + f" Дата: {date}".ljust(50) + "│\n")
    file.write("│" + f" Эксперимент: {experiment_name}".ljust(50) + "│\n")
    file.write("├" + "─" * 50 + "┤\n")
    file.write("│" + f" ВЫВОД: {conclusion}".ljust(50) + "│\n")
    file.write("└" + "─" * 50 + "┘\n")
print("Данные успешно сохранены в journal.txt")