dna_seq = input("Введите последовательность ДНК: ")
dna_upper = dna_seq.upper()
print("\n=== Анализ последовательности ДНК ===\n")
print(f"Введенная последовательность: {dna_seq}")
print(f"Последовательность в верхнем регистре: {dna_upper}\n")
count_A = dna_upper.count('A')
count_T = dna_upper.count('T')
count_G = dna_upper.count('G')
count_C = dna_upper.count('C')
total_length = len(dna_upper)
print("Подсчёт нуклеотидов:")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}\n")
print(f"Общая длина: {total_length} нуклеотидов")